name: dacbr_cep
description: Package integrante da suite DACBr, para consulta online de CEP.
version: 1.0.0
homepage: https://projetodacbr.com.br/
repository: https://github.com/mateuspenha/dacbr_cep
issue_tracker: https://github.com/mateuspenha/dacbr_cep/issues
author: Mateus Penha <mateuspenha@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+1
  xml2json: ^3.0.3

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0